# Generated by Django 5.1 on 2024-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
