# Generated by Django 5.1 on 2024-08-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
